on:
  schedule:
    - cron:  '0 7 * * *'
  workflow_dispatch:

name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
        with:
         repository: ${{ secrets.SOURCE_REPOSITORY }}
         fetch-depth: 0
      - name: go-version
        id: go_version
        run: |
          echo "VER=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          GOVER="$(curl -sLf 'https://golang.org/VERSION?m=text')"
          echo "GO_VERSION=${GOVER#go}" >> $GITHUB_OUTPUT
      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ steps.go_version.outputs.GO_VERSION }}'
          check-latest: true
      - name: build
        run: | 
          CGO_ENABLED=0 go build -o build -trimpath -ldflags "-s -w -buildid=" ./main
          zip -9vr build.zip build
      - name: Install minisign and sign
        run: |
          sudo apt-get -y install libsodium-dev
          git clone --depth 1 https://github.com/jedisct1/minisign.git
          cd minisign/src
          mkdir -p /tmp/bin
          cc -O2 -o /tmp/bin/minisign -D_GNU_SOURCE *.c -lsodium
          cd -
          /tmp/bin/minisign -v
          echo "${{ secrets.MINISIGN_SK }}" >> /tmp/minisign.key
          echo | /tmp/bin/minisign -s /tmp/minisign.key -Sm *.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build.zip*
          tag: ${{ steps.go_version.outputs.VER }}
          overwrite: true
          file_glob: true

